# Generated by Django 4.1.7 on 2023-04-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=254)),
                ('psw', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=13)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
