# Generated by Django 4.1.7 on 2023-04-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brd',
            field=models.DateField(auto_now=True),
        ),
    ]
